# Generated by Django 4.1.3 on 2022-12-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_created',
            new_name='date_sent',
        ),
    ]
